### ISSUE TITLE
Why is BallotFormat.ExternalIdentifier required?

### ISSUE THREAD

**Issue by jonahkagan** [usnistgov/BallotDefinition#7]
In general, it seems like the pattern in the Ballot Definition model is to allow the specification of optional external identifiers. The BallotFormat model, however, requires at least one external identifier. Why is this the case?

It's a bit of an obstacle to comply with this constraint, since there may not always be an external identifier to associate with the ballot format.

Could it be made optional like the other external identifier fields?

**Comment by JDziurlaj** [comment]
The `BallotFormat` is referenced by the microCDF BAL segment (as BAL-4), as there must be a stable identifier to correlate back to the correct `BallotFormat` so that the correct target areas can be activated for a given ballot style (for OMR style ballots).  See section 6.4 of the specification for more details.

**Comment by jonahkagan** [comment]
Ok, thank you
